project:
  type: website
  output-dir: docs

website:
  title: "Yeon"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Yeon0316
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: vapor
    css: styles.css



